In [32]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

### Загрузка данных

In [33]:
iris = load_iris()
X = iris.data
y = iris.target

In [34]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [35]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Разделение данных

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=17)

### Стандартизация данных

In [37]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [38]:
print(X_train.max(), X_train.min())
print(X_test.max(), X_test.min())

3.0210242733375394 -2.399879095641968
2.1515591163447136 -1.7222661745195302


### Преобразование в тензоры PyTorch

In [39]:
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)
y_test = torch.tensor(y_test, dtype=torch.long)

In [40]:
X_train.max()

tensor(3.0210)

In [41]:
X_test.min()

tensor(-1.7223)

In [42]:
y_train

tensor([0, 1, 0, 0, 1, 1, 1, 2, 1, 0, 1, 1, 0, 1, 2, 1, 1, 2, 1, 0, 2, 1, 1, 1,
        1, 0, 1, 2, 2, 0, 0, 2, 0, 2, 2, 0, 2, 0, 0, 1, 2, 0, 0, 1, 0, 2, 2, 0,
        0, 1, 2, 2, 0, 0, 2, 0, 0, 2, 2, 2, 2, 0, 2, 1, 0, 1, 0, 0, 1, 1, 1, 2,
        1, 2, 2, 1, 1, 2, 2, 1, 0, 2, 2, 1, 2, 1, 0, 1, 0, 1, 1, 2, 0, 1, 0, 2,
        1, 0, 0, 1, 0, 2, 0, 2, 0, 1, 2, 0, 0, 0, 2, 0, 0, 1, 0, 0, 1, 2, 2, 2])

### Определние архитектуры нейронной сети

In [43]:
class IrisNet(nn.Module):
    def __init__(self):
        super(IrisNet, self).__init__()
        self.fc1 = nn.Linear(4, 10)
        self.fc2 = nn.Linear(10, 3)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

### Инициализация модели

In [44]:
model = IrisNet()

### Определение функции потерь

In [49]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.0005)

### Обучение модели

In [51]:
epochs = 500
for epoch in range(epochs):
    optimizer.zero_grad()
    outputs = model(X_train)
    loss = criterion(outputs, y_train)
    loss.backward()
    optimizer.step()
    if (epoch+1)%10 == 0:
        print(f'Epoch [{epoch+1}/{epochs}], {loss.item():.4f}')

Epoch [10/500], 0.0664
Epoch [20/500], 0.0656
Epoch [30/500], 0.0647
Epoch [40/500], 0.0639
Epoch [50/500], 0.0631
Epoch [60/500], 0.0624
Epoch [70/500], 0.0616
Epoch [80/500], 0.0609
Epoch [90/500], 0.0602
Epoch [100/500], 0.0595
Epoch [110/500], 0.0589
Epoch [120/500], 0.0582
Epoch [130/500], 0.0576
Epoch [140/500], 0.0570
Epoch [150/500], 0.0564
Epoch [160/500], 0.0558
Epoch [170/500], 0.0553
Epoch [180/500], 0.0547
Epoch [190/500], 0.0542
Epoch [200/500], 0.0536
Epoch [210/500], 0.0531
Epoch [220/500], 0.0526
Epoch [230/500], 0.0521
Epoch [240/500], 0.0516
Epoch [250/500], 0.0512
Epoch [260/500], 0.0507
Epoch [270/500], 0.0502
Epoch [280/500], 0.0498
Epoch [290/500], 0.0494
Epoch [300/500], 0.0489
Epoch [310/500], 0.0485
Epoch [320/500], 0.0481
Epoch [330/500], 0.0477
Epoch [340/500], 0.0473
Epoch [350/500], 0.0469
Epoch [360/500], 0.0465
Epoch [370/500], 0.0462
Epoch [380/500], 0.0458
Epoch [390/500], 0.0455
Epoch [400/500], 0.0452
Epoch [410/500], 0.0448
Epoch [420/500], 0.0445
E

### Оценка модели

In [52]:
with torch.no_grad():
    model.eval()
    outputs = model(X_test)
    _, predicted = torch.max(outputs, 1)
    accuracy = (predicted == y_test).sum().item() / y_test.size(0)
    print(f'Accuracy: {accuracy:.2f}')

Accuracy: 0.97
